spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "c9kdtZ4l6AgUTt1OOtC5aRXVpGbmCaGQ9AszeD4PWx9mjPR1BAFlyrYGI7em+aHC"
    username: "RQTBWnqokg2vEx0ozMrffw=="
    password: "+A61rdnFkNZlIzmKGNShOw=="
  http:
    encoding:
      charset:    UTF-8
  mvc:
    view:
      prefix:     /jsp/
      suffix:     .jsp
      
server:
  port : 8080
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  config-location: classpath:mybatis-config.xml